language: php

php:
  - 7.1
  - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - travis_retry composer dump-autoload -o

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

notifications:
    email: false